version: "3.6"
services:
  postgres:
    restart: always
    image: postgres:14.2
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    env_file:
      - .env